version: '3.7'

networks:
  adapter-net:
    driver: bridge

services:
  get-farmer-crop-data:
    image: ghcr.io/datakaveri/adex-get-farmer-crop-data:1.0.0
    volumes:
      - ./secrets/config.ini:/usr/share/app/secrets/config.ini
    restart: on-failure
    networks: 
      - adapter-net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
